In [23]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [172]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [174]:
type(my_list)

list

In [176]:
arr=np.array(my_list)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.arange(3.0)

array([0., 1., 2.])

In [26]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.arange(20,10)

array([], dtype=int32)

In [36]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [38]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [42]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [44]:
np.arange()

TypeError: arange() requires stop to be specified.

In [46]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [50]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [54]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [56]:
np.zeros(3)

array([0., 0., 0.])

In [58]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [60]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [62]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [64]:
zero=np.array([2,2])

print(zero)

[2 2]


In [70]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [72]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [74]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [82]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [84]:
np.ones(3)

array([1., 1., 1.])

In [86]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [88]:
np.ones(4)

array([1., 1., 1., 1.])

In [90]:
n

(6, 7)

In [92]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [94]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [96]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [98]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [1]:
range(5)

range(0, 5)

In [3]:
r = range(5)
r

range(0, 5)

In [5]:
for i in r:
    print(i)

0
1
2
3
4


In [7]:
list(range(5))

[0, 1, 2, 3, 4]

In [9]:
range(1,10)

range(1, 10)

In [11]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list(range(1,10,3))

[1, 4, 7]

In [15]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [17]:
rand(3,2)

NameError: name 'rand' is not defined

In [19]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [25]:
np.random.rand(5)

array([0.52230689, 0.5904132 , 0.1922358 , 0.54533773, 0.7558652 ])

In [27]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [29]:
np.random.rand(2,4)

array([[0.20603543, 0.93452799, 0.6813939 , 0.04777341],
       [0.2519151 , 0.88655788, 0.8538091 , 0.75922044]])

In [31]:
np.random.randint(2,4)

3

In [33]:
np.random.randint(2,20)

13

In [35]:
np.random.randint(0,1) 

0

In [37]:
np.random.randint(10,20,5)

array([19, 15, 10, 10, 10])

In [39]:
np.random.randint(1,6,4)

array([3, 2, 4, 3])

In [41]:
np.random.rand(3)

array([0.42773569, 0.85691609, 0.66580572])

In [43]:
np.random.randint(1)  

0

In [45]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [47]:
np.random.randint(-30,20,10) 

array([-14,  17,   6, -15, -13, -14,  -8,   1,   1,  17])

In [50]:
np.random.randint(20,30,10) 

array([25, 20, 24, 25, 23, 26, 20, 22, 22, 27])

In [52]:
np.random.randint(10,21,3)

array([20, 20, 12])

In [54]:
np.random.randint(1,12,10)

array([ 3,  2,  5,  1, 11,  3,  1,  5,  4,  8])

In [56]:
np.random.randint(10,40,(10,10))

array([[29, 29, 24, 11, 36, 15, 12, 27, 24, 15],
       [15, 23, 29, 18, 30, 35, 32, 25, 29, 11],
       [17, 16, 18, 30, 14, 29, 16, 35, 33, 10],
       [23, 18, 18, 18, 16, 38, 31, 27, 15, 13],
       [29, 13, 15, 37, 14, 20, 17, 36, 10, 29],
       [15, 18, 13, 19, 24, 21, 12, 28, 23, 39],
       [23, 22, 13, 38, 24, 15, 33, 17, 17, 39],
       [28, 23, 26, 19, 30, 24, 23, 14, 35, 23],
       [34, 12, 24, 14, 19, 18, 36, 29, 12, 14],
       [20, 14, 15, 10, 36, 30, 26, 16, 25, 31]])

In [59]:
np.random.randint(1,100,(12,12)) 

array([[56, 66, 36, 51, 77, 36,  4, 47, 78, 25, 79, 82],
       [85, 43, 93, 49, 16, 36, 29, 33, 99, 22, 37, 35],
       [50, 83, 43, 10, 26,  6, 97, 17, 30, 85, 38, 99],
       [34, 26, 88, 63, 81, 48, 40, 54, 66, 20, 53, 29],
       [43, 60, 73, 28, 27,  9, 20, 17, 45, 62, 88, 63],
       [89, 94, 87, 87, 82, 44, 19, 30, 69, 60, 59, 28],
       [90, 80, 29, 30, 53, 99,  3, 67, 13, 19, 19, 29],
       [91, 47, 64, 72, 86, 29, 32, 97, 57, 48, 95, 95],
       [82, 77,  8, 80, 93, 93, 55, 72, 39, 77, 34, 55],
       [15, 72, 14,  9, 74,  8, 54,  2, 97, 10, 13, 16],
       [75, 83, 74, 86, 94, 32, 82, 74, 82, 49, 66, 20],
       [33, 16, 57, 12, 33, 88, 28, 47, 77, 77, 86, 13]])

In [61]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [65]:
b = np.random.randint(10,20,(5,4))
b


array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [67]:
type(b)

numpy.ndarray

In [69]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [71]:
b[:] 

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [73]:
b[1:3]

array([[10, 12, 10, 19],
       [13, 15, 11, 13]])

In [75]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [77]:
b[1,2]

10

In [79]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [81]:
b[1,3]

19

In [83]:
b[1,-1]

19

In [85]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [87]:
b[2:3]

array([[13, 15, 11, 13]])

In [89]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [91]:
b[0:-2] 

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13]])

In [93]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [95]:
b[0,2] 

14

In [97]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [99]:
b[-5,-3] 

15

In [101]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [103]:
b[-4,2] 

10

In [105]:
np.random.randint(10,20,(4,4))

array([[18, 12, 17, 12],
       [10, 17, 13, 16],
       [17, 10, 11, 11],
       [12, 18, 16, 15]])

In [107]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [109]:
b[-4,-2]

10

In [111]:
b

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

In [113]:
b[-4:2] 

array([[10, 12, 10, 19]])

In [115]:
b[:]

array([[11, 15, 14, 12],
       [10, 12, 10, 19],
       [13, 15, 11, 13],
       [13, 16, 12, 15],
       [18, 19, 16, 14]])

Operations

In [118]:
a = np.random.randint(10,20,10)
a

array([13, 11, 17, 16, 14, 18, 14, 13, 11, 16])

In [120]:
id(a)

2653875464560

In [178]:
arr

array([0, 1, 2, 3, 4, 5])

In [124]:
arr2 = np.random.randint(0,100,(10,10))

In [126]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [180]:
arr

array([0, 1, 2, 3, 4, 5])

In [182]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [184]:
arr


array([0, 1, 2, 3, 4, 5])

In [186]:
arr[:4] 

array([0, 1, 2, 3])

In [188]:
arr2[:]


array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [190]:
arr2[0:5]

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1]])

In [192]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [194]:
arr2[1,4] 

6

In [196]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [198]:
arr2[-5,5] 

83

In [200]:
arr2[-5,-5] 

83

In [202]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [204]:
arr2[-5,-5]

83

In [206]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [208]:
arr2[-1,-2]


91

In [210]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [212]:
arr2[::-1]

array([[16, 42, 10, 30, 25, 84, 18, 40, 91, 63],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [76, 48, 53, 32, 10, 57, 15, 73, 24, 70]])

In [214]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [216]:
arr2[::-2] 

array([[16, 42, 10, 30, 25, 84, 18, 40, 91, 63],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69]])

In [218]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [220]:
arr2[::-3]

array([[16, 42, 10, 30, 25, 84, 18, 40, 91, 63],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [76, 48, 53, 32, 10, 57, 15, 73, 24, 70]])

In [222]:
arr2

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50],
       [51, 64, 66, 92, 62, 37, 43, 35, 95,  2],
       [78, 67, 39, 95, 65, 37, 64, 77, 90, 63],
       [16, 42, 10, 30, 25, 84, 18, 40, 91, 63]])

In [224]:
arr2[:-3] 

array([[76, 48, 53, 32, 10, 57, 15, 73, 24, 70],
       [67, 49, 80, 40,  6, 78, 32, 35, 89, 69],
       [75, 67, 93, 99, 97, 45, 99,  4, 17, 46],
       [65, 71, 69,  4, 23, 40, 50,  2, 68,  0],
       [96,  3, 74, 41, 46, 12, 97, 65, 49,  1],
       [ 3, 92, 76, 84, 48, 83, 99, 61, 42,  7],
       [98,  4, 65, 15, 62, 58, 94,  7, 20, 50]])

In [226]:
arr

array([0, 1, 2, 3, 4, 5])

In [228]:
arr.max() 

5

In [230]:
arr.min()

0

In [232]:
arr

array([0, 1, 2, 3, 4, 5])

In [234]:
arr.mean()

2.5

In [236]:
arr

array([0, 1, 2, 3, 4, 5])

In [238]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [240]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

Without work on import* can you please find the median, mode)

In [243]:
arr

array([0, 1, 2, 3, 4, 5])

In [245]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [247]:
arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [249]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [251]:
arr

array([0, 1, 2, 3, 4, 5])

In [253]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [255]:
arr

array([0, 1, 2, 3, 4, 5])

In [257]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [259]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [261]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [263]:
arr

array([0, 1, 2, 3, 4, 5])

In [265]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [267]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [269]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [271]:
arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [273]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [275]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [277]:
arr

array([0, 1, 2, 3, 4, 5])

In [279]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

Indexing

In [282]:
mat = np.arange(0,100).reshape(10,10) 

In [284]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [286]:
row = 4
col = 5

In [288]:
col

5

In [290]:
row

4

In [292]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [294]:
mat[row,col] 

45

In [296]:
mat[4,5] 

45

In [298]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [300]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [302]:
col = 6


In [304]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [306]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [308]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [310]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [312]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [314]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [316]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [318]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [320]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [322]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [324]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [326]:
row

4

In [328]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [330]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [332]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [334]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [336]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [338]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [340]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [342]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [344]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [346]:
row

4

In [348]:
col

6

In [350]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [352]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [354]:
mat[1,4]

14

In [356]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [358]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [360]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [362]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [364]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [366]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [368]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [370]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [372]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [374]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [376]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [378]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [380]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [382]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [384]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [386]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [388]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [390]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [392]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [394]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [396]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [398]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [400]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [402]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [404]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [406]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [408]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [410]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [412]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [414]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [416]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [418]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [420]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [422]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [424]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [426]:
mat[0,1]

1

In [428]:
mat[1,6]

16

In [430]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [432]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [434]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [436]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [438]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [440]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [442]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [444]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [446]:
mat[3,5]

35

In [448]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [450]:
mat[1:2,2:4] 

array([[12, 13]])

In [452]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [454]:
mat[2:3,2:3] 

array([[22]])

In [456]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [458]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [460]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [462]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [464]:
mat[2:3,4:5]

array([[24]])

Masking

In [467]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [469]:
id(mat)

2653879519824

In [471]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [473]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [475]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [477]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [479]:
mat[mat==50] 

array([50])

In [481]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [483]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [485]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [487]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [489]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [491]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [493]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [495]:
a4 = mat[mat==50]
a4

array([50])

python program to generat otp

In [512]:
import random
def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
length = 4  # You can change this to any length you prefer
otp = generate_otp(length)
print(f"Your OTP is: {otp}")

Your OTP is: 5225


In [514]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [516]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [518]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x00000269E7A952C0>


In [520]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
